[package]
name = "srml-support"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
hex-literal = { version = "0.1.0", optional = true }
serde = { version = "1.0", default_features = false }
serde_derive = { version = "1.0", optional = true }
sr-std = { path = "../../sr-std", default_features = false }
sr-io = { path = "../../sr-io", default_features = false }
substrate-primitives = { path = "../../primitives", default_features = false }
parity-codec = { path = "../../../codec", default_features = false }
substrate-metadata = { path = "../../metadata", default_features = false }

[dev-dependencies]
pretty_assertions = "0.5.1"
serde_json = { version = "1.0" }
parity-codec-derive = { path = "../../../codec/derive" }

[features]
default = ["std"]
std = [
	"hex-literal",
	"serde/std",
	"serde_derive",
	"substrate-primitives/std",
	"sr-io/std",
	"parity-codec/std",
	"sr-std/std",
	"substrate-metadata/std",
]
nightly = []
strict = []
