[package]
name = "node-testing"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Test utilities for Substrate node."
edition = "2018"

[dependencies]
balances = { package = "paint-balances", path = "../../../palette/balances" }
client = { package = "substrate-client", path = "../../../client/" }
codec = { package = "parity-scale-codec", version = "1.0.0" }
contracts = { package = "paint-contracts", path = "../../../palette/contracts" }
grandpa = { package = "paint-grandpa", path = "../../../palette/grandpa" }
indices = { package = "paint-indices", path = "../../../palette/indices" }
keyring = { package = "substrate-keyring", path = "../../../primitives/keyring" }
node-executor = { path = "../executor" }
node-primitives = { path = "../primitives" }
node-runtime = { path = "../runtime" }
primitives = { package = "substrate-primitives", path = "../../../primitives/core" }
runtime-io = { package = "sr-io", path = "../../../primitives/sr-io" }
runtime_support = { package = "paint-support", path = "../../../palette/support" }
session = { package = "paint-session", path = "../../../palette/session" }
sr-primitives = { path = "../../../primitives/sr-primitives" }
staking = { package = "paint-staking", path = "../../../palette/staking" }
substrate-executor = { path = "../../../client/executor" }
system = { package = "paint-system", path = "../../../palette/system" }
test-client = { package = "substrate-test-client", path = "../../../test/utils/client" }
timestamp = { package = "paint-timestamp", path = "../../../palette/timestamp" }
transaction-payment = { package = "paint-transaction-payment", path = "../../../palette/transaction-payment" }
treasury = { package = "paint-treasury", path = "../../../palette/treasury" }
wabt = "0.9.2"
