# Number of days of inactivity before an issue becomes stale
daysUntilStale: 30
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 14
# Issues with these labels will never be considered stale
exemptLabels:
  - "D9-needsaudit 👮"
  - "I5-documentation 📄"
  - "I6-refactor 🧹"
  - "I7-footprint 👣"
  - "I8-enhancement 🎁"
  - "I9-meta 📦"
  - "P7-nicetohave"
  - "P9-somedaymaybe"
  - "Z1-mentor"
  - "Z2-bounty"
# Label to use when marking an issue as stale
staleLabel: "A3-stale"
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  Hey, is anyone still working on this? Due to the inactivity this issue has
  been automatically marked as stale. It will be closed if no further activity
  occurs. Thank you for your contributions.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
# Set to true to ignore issues in a project (defaults to false)
exemptProjects: true
