# Request an environment that provides sudo (that goes with larger containers)
# and a minimal language environment.
sudo: true
language: rust

cache: cargo

branches:
  only:
  - master

env:
  global:
    - RUST_BACKTRACE=1
  matrix:
    - rust: stable
      env: TARGET=native
    - rust: nightly
      env: TARGET=wasm

before_install:
    # Check how much space we've got on this machine.
  - df -h

install:
  - travis_wait 30 cargo update --locked

script:
  - ./ci/script.sh

after_success:
  - if [ "$TARGET" == "wasm" ] && [ "$TRAVIS_PULL_REQUEST" != "true" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
      ./ci/publish-wasm.sh;
    fi

after_script:
  # Check how much free disk space left after the build
  - df -h
