[workspace]
members = [
	"codec",
	"codec/derive",
	"environmental",
	"core/bft",
	"core/cli",
	"core/client",
	"core/client/db",
	"core/executor",
	"core/extrinsic-pool",
	"core/keyring",
	"core/metadata",
	"core/misbehavior-check",
	"core/network",
	"core/primitives",
	"core/rpc",
	"core/rpc-servers",
	"core/runtime-io",
	"core/runtime-sandbox",
	"core/runtime-std",
	"core/runtime-version",
	"core/runtime/support",
	"core/runtime/balances",
	"core/runtime/consensus",
	"core/runtime/contract",
	"core/runtime/council",
	"core/runtime/democracy",
	"core/runtime/example",
	"core/runtime/executive",
	"core/runtime-primitives",
	"core/runtime/session",
	"core/runtime/staking",
	"core/runtime/system",
	"core/runtime/timestamp",
	"core/runtime/treasury",
	"core/serializer",
	"core/service",
	"core/state-db",
	"core/state-machine",
	"core/test-runtime",
	"core/telemetry",
	"core/keystore",
	"node",
	"node/cli",
	"node/api",
	"node/consensus",
	"node/executor",
	"node/network",
	"node/primitives",
	"node/runtime",
	"node/service",
	"node/transaction-pool",
	"subkey",
]
exclude = [
	"node/runtime/wasm",
	"core/executor/wasm",
	"pwasm-alloc",
	"pwasm-libc",
	"core/test-runtime/wasm",
]

[badges]
travis-ci = { repository = "paritytech/substrate", branch = "master" }
maintenance = { status = "actively-developed" }
is-it-maintained-issue-resolution = { repository = "paritytech/substrate" }
is-it-maintained-open-issues = { repository = "paritytech/substrate" }

[profile.release]
# Substrate runtime requires unwinding.
panic = "unwind"
