[package]
name = "node-runtime"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
integer-sqrt = { git = "https://github.com/paritytech/integer-sqrt-rs.git", branch = "master" }
safe-mix = { version = "1.0", default_features = false}
node-primitives = { path = "../../primitives", default-features = false }
substrate-codec-derive = { path = "../../../core/codec/derive" }
substrate-codec = { path = "../../../core/codec", default-features = false }
substrate-primitives = { path = "../../../core/primitives", default-features = false }
substrate-runtime-std = { path = "../../../core/runtime-std", default-features = false }
substrate-runtime-io = { path = "../../../core/runtime-io", default-features = false }
substrate-runtime-support = { path = "../../../runtime/support", default-features = false }
substrate-runtime-balances = { path = "../../../runtime/balances", default-features = false }
substrate-runtime-consensus = { path = "../../../runtime/consensus", default-features = false }
substrate-runtime-contract = { path = "../../../runtime/contract", default-features = false }
substrate-runtime-council = { path = "../../../runtime/council", default-features = false }
substrate-runtime-democracy = { path = "../../../runtime/democracy", default-features = false }
substrate-runtime-executive = { path = "../../../runtime/executive", default-features = false }
substrate-runtime-primitives = { path = "../../../runtime/primitives", default-features = false }
substrate-runtime-session = { path = "../../../runtime/session", default-features = false }
substrate-runtime-staking = { path = "../../../runtime/staking", default-features = false }
substrate-runtime-system = { path = "../../../runtime/system", default-features = false }
substrate-runtime-timestamp = { path = "../../../runtime/timestamp", default-features = false }
substrate-runtime-treasury = { path = "../../../runtime/treasury", default-features = false }
substrate-runtime-version = { path = "../../../runtime/version", default-features = false }

[profile.release]
panic = "abort"
lto = true

[workspace]
members = []
