[package]
name = "node-runtime"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
integer-sqrt = { git = "https://github.com/paritytech/integer-sqrt-rs.git", branch = "master" }
safe-mix = { version = "1.0", default_features = false}
parity-codec-derive = { version = "~2.0.1" }
parity-codec = { version = "~2.0.1", default_features = false }
substrate-primitives = { path = "../../../core/primitives", default_features = false }
sr-std = { path = "../../../core/sr-std", default_features = false }
sr-io = { path = "../../../core/sr-io", default_features = false }
srml-support = { path = "../../../srml/support", default_features = false }
srml-balances = { path = "../../../srml/balances", default_features = false }
srml-consensus = { path = "../../../srml/consensus", default_features = false }
srml-contract = { path = "../../../srml/contract", default_features = false }
srml-council = { path = "../../../srml/council", default_features = false }
srml-democracy = { path = "../../../srml/democracy", default_features = false }
srml-executive = { path = "../../../srml/executive", default_features = false }
sr-primitives = { path = "../../../core/sr-primitives", default_features = false }
srml-session = { path = "../../../srml/session", default_features = false }
srml-staking = { path = "../../../srml/staking", default_features = false }
srml-system = { path = "../../../srml/system", default_features = false }
srml-timestamp = { path = "../../../srml/timestamp", default_features = false }
srml-treasury = { path = "../../../srml/treasury", default_features = false }
sr-version = { path = "../../../core/sr-version", default_features = false }
node-primitives = { path = "../../primitives", default_features = false }

[features]
default = []
std = [
	"safe-mix/std",
	"parity-codec/std",
	"substrate-primitives/std",
	"sr-std/std",
	"sr-io/std",
	"srml-support/std",
	"srml-balances/std",
	"srml-consensus/std",
	"srml-contract/std",
	"srml-council/std",
	"srml-democracy/std",
	"srml-executive/std",
	"sr-primitives/std",
	"srml-session/std",
	"srml-staking/std",
	"srml-system/std",
	"srml-timestamp/std",
	"srml-treasury/std",
	"sr-version/std",
	"node-primitives/std",
]

[profile.release]
panic = "abort"
lto = true

[workspace]
members = []
