[package]
name = "node-runtime"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
integer-sqrt = { git = "https://github.com/paritytech/integer-sqrt-rs.git", branch = "master" }
safe-mix = { version = "1.0", default_features = false}
parity-codec-derive = { path = "../../../codec/derive" }
parity-codec = { path = "../../../codec", default-features = false }
substrate-primitives = { path = "../../../core/primitives", default-features = false }
sr-std = { path = "../../../core/sr-std", default-features = false }
sr-io = { path = "../../../core/sr-io", default-features = false }
substrate-runtime-support = { path = "../../../core/runtime/support", default-features = false }
substrate-runtime-balances = { path = "../../../core/runtime/balances", default-features = false }
substrate-runtime-consensus = { path = "../../../core/runtime/consensus", default-features = false }
substrate-runtime-contract = { path = "../../../core/runtime/contract", default-features = false }
substrate-runtime-council = { path = "../../../core/runtime/council", default-features = false }
substrate-runtime-democracy = { path = "../../../core/runtime/democracy", default-features = false }
substrate-runtime-executive = { path = "../../../core/runtime/executive", default-features = false }
sr-primitives = { path = "../../../core/sr-primitives", default-features = false }
substrate-runtime-session = { path = "../../../core/runtime/session", default-features = false }
substrate-runtime-staking = { path = "../../../core/runtime/staking", default-features = false }
substrate-runtime-system = { path = "../../../core/runtime/system", default-features = false }
substrate-runtime-timestamp = { path = "../../../core/runtime/timestamp", default-features = false }
substrate-runtime-treasury = { path = "../../../core/runtime/treasury", default-features = false }
sr-version = { path = "../../../core/sr-version", default-features = false }
node-primitives = { path = "../../primitives", default-features = false }

[features]
default = []
std = [
	"safe-mix/std",
	"parity-codec/std",
	"substrate-primitives/std",
	"sr-std/std",
	"sr-io/std",
	"substrate-runtime-support/std",
	"substrate-runtime-balances/std",
	"substrate-runtime-consensus/std",
	"substrate-runtime-contract/std",
	"substrate-runtime-council/std",
	"substrate-runtime-democracy/std",
	"substrate-runtime-executive/std",
	"sr-primitives/std",
	"substrate-runtime-session/std",
	"substrate-runtime-staking/std",
	"substrate-runtime-system/std",
	"substrate-runtime-timestamp/std",
	"substrate-runtime-treasury/std",
	"sr-version/std",
	"node-primitives/std",
]

[profile.release]
panic = "abort"
lto = true

[workspace]
members = []
