[package]
name = "phragmen"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
sr-primitives = { path = "../../core/sr-primitives" }
rstd = { package = "sr-std", path = "../sr-std", default-features = false }

[features]
default = ["std"]
std = [
	"rstd/std",
	"sr-primitives/std",
]
