[package]
description = "Grafana data source server"
name = "grafana-data-source"
version = "2.0.0"
license = "GPL-3.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
hyper = { version = "0.13.0-alpha.4", features = ["unstable-stream"] }
futures-util-preview = "=0.3.0-alpha.19"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
lazy_static = "1.4"
parking_lot = "0.9"
futures-timer = "1.0"
derive_more = "0.15"
