[package]
name = "node-runtime"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
rustc-hex = "1.0"
hex-literal = "0.1.0"
log = { version = "0.3", optional = true }
serde = { version = "1.0", default_features = false }
serde_derive = { version = "1.0", optional = true }
safe-mix = { version = "1.0", default_features = false}
parity-codec = { path = "../../codec" }
parity-codec-derive = { path = "../../codec/derive" }
sr-std = { path = "../../core/sr-std" }
sr-io = { path = "../../core/sr-io" }
substrate-runtime-support = { path = "../../core/runtime/support" }
substrate-primitives = { path = "../../core/primitives" }
substrate-keyring = { path = "../../core/keyring" }
substrate-runtime-balances = { path = "../../core/runtime/balances" }
substrate-runtime-consensus = { path = "../../core/runtime/consensus" }
substrate-runtime-contract = { path = "../../core/runtime/contract" }
substrate-runtime-council = { path = "../../core/runtime/council" }
substrate-runtime-democracy = { path = "../../core/runtime/democracy" }
substrate-runtime-executive = { path = "../../core/runtime/executive" }
sr-primitives = { path = "../../core/sr-primitives" }
substrate-runtime-session = { path = "../../core/runtime/session" }
substrate-runtime-staking = { path = "../../core/runtime/staking" }
substrate-runtime-system = { path = "../../core/runtime/system" }
substrate-runtime-timestamp = { path = "../../core/runtime/timestamp" }
substrate-runtime-treasury = { path = "../../core/runtime/treasury" }
sr-version = { path = "../../core/sr-version" }
node-primitives = { path = "../primitives" }

[features]
default = ["std"]
std = [
	"parity-codec/std",
	"substrate-primitives/std",
	"sr-std/std",
	"sr-io/std",
	"substrate-runtime-support/std",
	"substrate-runtime-balances/std",
	"substrate-runtime-consensus/std",
	"substrate-runtime-contract/std",
	"substrate-runtime-council/std",
	"substrate-runtime-democracy/std",
	"substrate-runtime-executive/std",
	"sr-primitives/std",
	"substrate-runtime-session/std",
	"substrate-runtime-staking/std",
	"substrate-runtime-system/std",
	"substrate-runtime-timestamp/std",
	"substrate-runtime-treasury/std",
	"sr-version/std",
	"node-primitives/std",
	"serde_derive",
	"serde/std",
	"log",
	"safe-mix/std"
]
