[package]
name = "node-runtime"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
rustc-hex = "1.0"
hex-literal = "0.1.0"
log = { version = "0.3", optional = true }
serde = { version = "1.0", default_features = false }
serde_derive = { version = "1.0", optional = true }
safe-mix = { version = "1.0", default_features = false}
parity-codec = { path = "../../codec" }
parity-codec-derive = { path = "../../codec/derive" }
sr-std = { path = "../../core/sr-std" }
sr-io = { path = "../../core/sr-io" }
srml-support = { path = "../../core/srml/support" }
substrate-primitives = { path = "../../core/primitives" }
substrate-keyring = { path = "../../core/keyring" }
srml-balances = { path = "../../core/srml/balances" }
srml-consensus = { path = "../../core/srml/consensus" }
srml-contract = { path = "../../core/srml/contract" }
srml-council = { path = "../../core/srml/council" }
srml-democracy = { path = "../../core/srml/democracy" }
srml-executive = { path = "../../core/srml/executive" }
sr-primitives = { path = "../../core/sr-primitives" }
srml-session = { path = "../../core/srml/session" }
srml-staking = { path = "../../core/srml/staking" }
srml-system = { path = "../../core/srml/system" }
srml-timestamp = { path = "../../core/srml/timestamp" }
srml-treasury = { path = "../../core/srml/treasury" }
sr-version = { path = "../../core/sr-version" }
node-primitives = { path = "../primitives" }

[features]
default = ["std"]
std = [
	"parity-codec/std",
	"substrate-primitives/std",
	"sr-std/std",
	"sr-io/std",
	"srml-support/std",
	"srml-balances/std",
	"srml-consensus/std",
	"srml-contract/std",
	"srml-council/std",
	"srml-democracy/std",
	"srml-executive/std",
	"sr-primitives/std",
	"srml-session/std",
	"srml-staking/std",
	"srml-system/std",
	"srml-timestamp/std",
	"srml-treasury/std",
	"sr-version/std",
	"node-primitives/std",
	"serde_derive",
	"serde/std",
	"log",
	"safe-mix/std"
]
