[package]
name = "substrate-consensus-common"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Common utilities for substrate consensus"

[dependencies]
substrate-primitives = { path= "../../primitives" }
error-chain = "0.12"
futures = "0.1"
sr-version = { path = "../../sr-version" }
sr-primitives = { path = "../../sr-primitives" }
tokio = "0.1.7"
parity-codec = "2.1"
parity-codec-derive = "2.0"
substrate-client = { path = "../../../core/client" }
slog = { version = "^2", optional = true }
substrate-telemetry = { path = "../../../core/telemetry", optional = true }
log = "0.4"
substrate-transaction-pool = { path = "../../../core/transaction-pool" }
parking_lot = "0.4"

[features]
default = ["std"]
std = [
    "slog",
    "substrate-telemetry",
]