[package]
name = "substrate-consensus-common"
version = "1.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Common utilities for substrate consensus"
edition = "2018"

[dependencies]
crossbeam-channel = "0.3.4"
libp2p = { git = "https://github.com/libp2p/rust-libp2p", rev = "a953b613cf543708ec3aa65c66921934310f8069", default-features = false }
log = "0.4"
primitives = { package = "substrate-primitives", path= "../../primitives" }
inherents = { package = "substrate-inherents", path = "../../inherents" }
error-chain = "0.12"
futures = "0.1"
runtime_version = { package = "sr-version", path = "../../sr-version" }
runtime_primitives = { package = "sr-primitives", path = "../../sr-primitives" }
tokio = "0.1.7"
parity-codec = { version = "3.3", features = ["derive"] }

[dev-dependencies]
test_client = { package = "substrate-test-client", path = "../../test-client" }

[features]
default = []
test-helpers = []