[package]
name = "subhd"
version = "0.1.0"
authors = ["chester"]
edition = "2018"

[dependencies]
hex-view = "0.1.3"
primitives = { package = "substrate-primitives",  version = "*", path = "../../core/primitives" }
wookong-solo = {path="../../../solo"}

[build-dependencies]
cc = "1.0"
