[package]
description = "Substrate offchain workers"
name = "substrate-offchain"
version = "2.0.0"
license = "GPL-3.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
bytes = "0.4.12"
client = { package = "substrate-client", path = "../../core/client" }
futures-preview = "0.3.0-alpha.18"
log = "0.4.8"
fnv = "1.0.6"
futures01 = { package = "futures", version = "0.1" }
futures-timer = "0.3.0"
hyper = "0.12.33"
hyper-tls = "0.3.2"
offchain-primitives = { package = "substrate-offchain-primitives", path = "./primitives" }
codec = { package = "parity-scale-codec", version = "1.0.0", features = ["derive"] }
parking_lot = "0.9.0"
primitives = { package = "substrate-primitives", path = "../../core/primitives" }
rand = "0.7.0"
sr-primitives = { path = "../../core/sr-primitives" }
transaction_pool = { package = "substrate-transaction-pool", path = "../../core/transaction-pool" }
network = { package = "substrate-network", path = "../../core/network" }
keystore = { package = "substrate-keystore", path = "../keystore" }

[dev-dependencies]
env_logger = "0.6.2"
client-db = { package = "substrate-client-db", path = "../../core/client/db/", default-features = true }
test-client = { package = "substrate-test-runtime-client", path = "../../core/test-runtime/client" }
tokio = "0.1.22"

[features]
default = []
