[package]
name = "sp-transaction-storage-proof"
version = "3.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Transaction storage proof primitives"
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-inherents = { version = "3.0.0", default-features = false, path = "../inherents" }
sp-runtime = { version = "3.0.0", default-features = false, path = "../runtime" }
sp-std = { version = "3.0.0", default-features = false, path = "../std" }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }

sc-client-api = { version = "3.0.0", path = "../../client/api", optional = true }
sp-consensus = { version = "0.9.0", path = "../consensus/common", optional = true }
sp-trie = { version = "3.0.0", optional = true, path = "../trie" }
sp-core = { version = "3.0.0", path = "../core", optional = true }
log = { version = "0.4.8", optional = true }

[features]
default = [ "std" ]
std = [
	"codec/std",
	"sp-std/std",
	"sp-inherents/std",
	"sp-runtime/std",
	"sp-trie/std",
	"sp-consensus",
	"sp-core",
	"sc-client-api",
	"log",
]
