[package]
name = "substrate-rpc-servers"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
# http = { package = "jsonrpc-http-server", version = "11.0.0" }
# pubsub = { package = "jsonrpc-pubsub", version = "11.0.0" }
# ws = { package = "jsonrpc-ws-server", version = "11.0.0" }
http = { package = "jsonrpc-http-server", git = "https://github.com/paritytech/jsonrpc" }
pubsub = { package = "jsonrpc-pubsub", git = "https://github.com/paritytech/jsonrpc" }
ws = { package = "jsonrpc-ws-server", git = "https://github.com/paritytech/jsonrpc" }
log = "0.4"
serde = "1.0"
substrate-rpc = { path = "../rpc" }
sr-primitives = { path = "../sr-primitives" }
