[package]
name = "sc-rpc-server"
version = "3.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "Substrate RPC servers."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
log = "0.4.8"
prometheus-endpoint = { package = "substrate-prometheus-endpoint", path = "../../utils/prometheus", version = "0.9.0"}
serde = "1.0.101"
serde_json = "1.0.41"
sp-runtime = { version = "3.0.0", path = "../../primitives/runtime" }

[target.'cfg(not(target_os = "unknown"))'.dependencies]
futures-channel = "0.3"
jsonrpsee = { git = "https://github.com/paritytech/jsonrpsee", branch = "na-jsonrpsee-error-trait", features = ["server"] }
tokio = { version = "1", features = ["full"] }
