[package]
name = "substrate-header-metadata"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
lru = { version = "0.1.18" }
parking_lot = { version = "0.9.0" }
sr-primitives = { path = "../../sr-primitives" }
