[package]
name = "substrate-storage-procedural-tools"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
substrate-storage-procedural-tools-derive = { path = "./derive" }
proc-macro2 = "0.4"
quote = { version = "0.6" }
syn = { version = "0.15", features = ["full"] }
proc-macro-crate = "0.1.3"
