[package]
name = "sc-rpc"
version = "2.0.0-alpha.1"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "Substrate Client RPC"

[dependencies]
sc-rpc-api = { version = "0.8.0-alpha.1", path = "../rpc-api" }
sc-client-api = { version = "2.0.0-alpha.1", path = "../api" }
sc-client = { version = "0.8.0-alpha.1", path = "../" }
sp-api = { version = "2.0.0-alpha.1", path = "../../primitives/api" }
codec = { package = "parity-scale-codec", version = "1.0.0" }
futures = { version = "0.3.1", features = ["compat"] }
jsonrpc-pubsub = "14.0.3"
log = "0.4.8"
sp-core = { version = "2.0.0-alpha.1", path = "../../primitives/core" }
rpc = { package = "jsonrpc-core", version = "14.0.3" }
sp-version = { version = "2.0.0-alpha.1", path = "../../primitives/version" }
serde_json = "1.0.41"
sp-session = { version = "2.0.0-alpha.1", path = "../../primitives/session" }
sp-offchain = { version = "2.0.0-alpha.1", path = "../../primitives/offchain" }
sp-runtime = { version = "2.0.0-alpha.1", path = "../../primitives/runtime" }
sp-rpc = { version = "2.0.0-alpha.1", path = "../../primitives/rpc" }
sp-state-machine = { version = "0.8.0-alpha.1", path = "../../primitives/state-machine" }
sc-executor = { version = "0.8.0-alpha.1", path = "../executor" }
sc-keystore = { version = "2.0.0-alpha.1", path = "../keystore" }
sp-transaction-pool = { version = "2.0.0-alpha.1", path = "../../primitives/transaction-pool" }
sp-blockchain = { version = "2.0.0-alpha.1", path = "../../primitives/blockchain" }
hash-db = { version = "0.15.2", default-features = false }
parking_lot = "0.10.0"
