[package]
name = "chain-spec-builder"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
clap = { version = "~2.32", features = ["yaml"] }
substrate = { path = "../.." }
substrate-primitives = { path = "../../core/primitives" }
substrate-service = { path = "../../core/service" }
