[package]
name = "substrate-executor"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
derive_more = "0.15.0"
codec = { package = "parity-scale-codec", version = "1.0.0" }
runtime_io = { package = "sr-io", path = "../sr-io" }
primitives = { package = "substrate-primitives", path = "../primitives" }
trie = { package = "substrate-trie", path = "../trie" }
serializer = { package = "substrate-serializer", path = "../serializer" }
state_machine = { package = "substrate-state-machine", path = "../state-machine"  }
runtime_version = { package = "sr-version", path = "../sr-version" }
panic-handler = { package = "substrate-panic-handler", path = "../panic-handler" }
wasmi = "0.5.0"
parity-wasm = "0.40.1"
byteorder = "1.3.2"
lazy_static = "1.4.0"
parking_lot = "0.9.0"
log = "0.4.8"
libsecp256k1 = "0.2.2"
tiny-keccak = "1.5.0"

[dev-dependencies]
assert_matches = "1.3.0"
wabt = "0.9.1"
hex-literal = "0.2.1"
runtime-test = { package = "substrate-runtime-test", path = "runtime-test" }
substrate-client = { path = "../client" }
substrate-offchain = { path = "../offchain/" }

[features]
default = []
wasm-extern-trace = []
