[package]
name = "substrate-runtime-executive"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
hex-literal = "0.1.0"
serde = { version = "1.0", default_features = false }
serde_derive = { version = "1.0", optional = true }
substrate-codec = { path = "../../core/codec", default_features = false }
substrate-runtime-std = { path = "../../core/runtime-std", default_features = false }
substrate-runtime-io = { path = "../../core/runtime-io", default_features = false }
substrate-runtime-support = { path = "../support", default_features = false }
substrate-runtime-primitives = { path = "../primitives", default_features = false }
substrate-runtime-system = { path = "../system", default_features = false }

[dev-dependencies]
substrate-primitives = { path = "../../core/primitives" }
substrate-runtime-balances = { path = "../balances" }
substrate-codec-derive = { path = "../../core/codec/derive" }

[features]
default = ["std"]
std = [
	"substrate-runtime-std/std",
	"substrate-runtime-support/std",
	"serde/std",
	"serde_derive",
	"substrate-codec/std",
	"substrate-runtime-primitives/std",
	"substrate-runtime-io/std",
	"substrate-runtime-system/std",
]
