[package]
name = "substrate-misbehavior-check"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
parity-codec = { version = "~2.0.1", default_features = false }
substrate-primitives = { path = "../primitives", default_features = false }
sr-primitives = { path = "../sr-primitives", default_features = false }
sr-io = { path = "../sr-io", default_features = false }

[dev-dependencies]
substrate-bft = { path = "../bft" }
rhododendron = "0.3"
substrate-keyring = { path = "../keyring" }

[features]
default = ["std"]
std = ["parity-codec/std", "substrate-primitives/std", "sr-primitives/std", "sr-io/std"]
