[package]
name = "sr-arithmetic-fuzzer"
version = "0.1.0"
authors = ["Ashley <ashley.ruglys@gmail.com>"]
edition = "2018"

[dependencies]
honggfuzz = "0.5"
sr-arithmetic = { path = ".." }
primitive-types = "0.5.1"

[[bin]]
name = "biguint"
path = "src/biguint.rs"

[[bin]]
name = "rational128"
path = "src/rational128.rs"
