[package]
name = "sr-arithmetic-fuzzer"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
honggfuzz = "0.5"
sr-arithmetic = { path = ".." }
primitive-types = "0.6"
num-bigint = "0.2.3"
num-traits = "0.2.8"

[[bin]]
name = "biguint"
path = "src/biguint.rs"

[[bin]]
name = "rational128"
path = "src/rational128.rs"
