[package]
name = "substrate-storage"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", default-features = false }
serde_derive = { version = "1.0", optional = true }
parity-codec = { version = "3.0", default-features = false }
parity-codec-derive = { version = "3.0", default-features = false }
srml-metadata = { path = "../../srml/metadata", default-features = false }
sr-std = { path = "../sr-std", default-features = false }
runtime_io = { package = "sr-io", path = "../../core/sr-io", default-features = false }
sr-primitives = { path = "../sr-primitives", default-features = false }
substrate-storage-procedural = { path = "procedural" }
once_cell = { version = "0.1.6", default-features = false, optional = true }

[dev-dependencies]
pretty_assertions = "0.5.1"
runtime_support = { package = "srml-support", path = "../../srml/support" }

[features]
default = ["std"]
std = [
	"serde/std",
	"serde_derive",
	"parity-codec/std",
	"srml-metadata/std",
	"sr-std/std",
	"runtime_io/std",
	"sr-primitives/std",
	"once_cell",
]
