[package]
name = "srml-support-rpc"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>", "Andrew Dirksen <andrew@dirksen.com>"]
edition = "2018"

[dependencies]
futures = { version = "0.3.0", features = ["compat"] }
jsonrpc-client-transports = "14"
jsonrpc-core = "14"
parity-scale-codec = "1"
serde = "1"
srml-support = { path = "../" }
substrate-primitives-storage = { path = "../../../core/primitives/storage" }
substrate-rpc-api = { path = "../../../core/rpc/api" }

[dev-dependencies]
tokio = "0.1"
