[package]
name = "substrate-rpc-custom"
version = "0.1.0"
authors = ["Andrew Dirksen <andrew@dirksen.com>"]
edition = "2018"

[dependencies]
srml-support = { path = "../../../srml/support" }
substrate-rpc-api = { path = "../../../core/rpc/api" }
substrate-primitives-storage = { path = "../../../core/primitives/storage" }
jsonrpc-client-transports = "14"
jsonrpc-core = "14"
parity-scale-codec = "1"
futures-preview = { version = "0.3.0-alpha.19", features = ["compat"] }
serde = "1"

[dev-dependencies]
srml-system = { path = "../../../srml/system" }
srml-support = { path = "../../../srml/support" }
jsonrpc-client-transports = { version = "14", features = ["http"] }
tokio = "0.1"
