[package]
name = "sc-service-types"
version = "0.8.0-rc5"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "Easy to use type definitions"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sc-service = { path = "..", version = "0.8.0-rc4"}
sc-finality-grandpa = { path = "../../finality-grandpa", version = "0.8.0-rc4"}
sc-consensus = { path = "../../consensus/common", version = "0.8.0-rc4"}
sc-consensus-aura = { path = "../../consensus/aura", version = "0.8.0-rc4"}
sc-consensus-babe = { path = "../../consensus/babe", version = "0.8.0-rc4"}
sc-transaction-pool = { path = "../../transaction-pool", version = "2.0.0-rc4"}
sc-network = { path = "../../network" }
sp-api = { path = "../../../primitives/api" }
