[package]
name = "substrate-test-runtime"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
log = { version = "0.3", optional = true }
hex-literal = { version = "0.1.0", optional = true }
parity-codec = { version = "~2.0.1", default_features = false }
parity-codec-derive = { version = "~2.0.1", default_features = false }
substrate-primitives = { path = "../../primitives", default_features = false }
sr-std = { path = "../../sr-std", default_features = false }
sr-io = { path = "../../sr-io", default_features = false }
sr-version = { path = "../../sr-version", default_features = false }
sr-primitives = { path = "../../sr-primitives", default_features = false }
srml-support = { path = "../../../srml/support", default_features = false }

[features]
default = []
std = [
	"log",
	"hex-literal",
	"parity-codec/std",
	"sr-std/std",
	"sr-io/std",
	"srml-support/std",
	"sr-version/std",
	"substrate-primitives/std",
	"sr-primitives/std"
]

[lib]
crate-type = ["cdylib"]

[profile.release]
panic = "abort"
lto = true

[workspace]
members = []
