[package]
name = "sr-api"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
parity-codec = { version = "2.1", default-features = false }
parity-codec-derive = "2.1"
sr-std = { path = "../sr-std", default-features = false }
sr-primitives = { path = "../sr-primitives", default-features = false }
substrate-primitives = { path = "../primitives", default-features = false }
sr-version = { path = "../sr-version", default-features = false }
error-chain = { version = "0.12", optional = true }
substrate-state-machine = { path = "../state-machine", optional = true }

[features]
default = ["std"]
std = [
	"sr-std/std",
	"parity-codec/std",
	"sr-primitives/std",
	"substrate-primitives/std",
	"sr-version/std",
	"error-chain",
	"substrate-state-machine"
]
