[package]
name = "node-api"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
node-runtime = { path = "../runtime" }
node-primitives = { path = "../primitives" }
substrate-client = { path = "../../substrate/client" }
substrate-primitives = { path = "../../substrate/primitives" }

[dev-dependencies]
substrate-keyring = { path = "../../substrate/keyring" }
