[package]
name = "substrate-service"
version = "0.3.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
futures = "0.1.17"
parking_lot = "0.4"
error-chain = "0.12"
lazy_static = "1.0"
log = "0.3"
slog = "^2"
tokio = "0.1.7"
exit-future = "0.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
target_info = "0.1"
substrate-keystore = { path = "../keystore" }
substrate-runtime-io = { path = "../runtime-io" }
substrate-runtime-primitives = { path = "../../runtime/primitives" }
substrate-primitives = { path = "../primitives" }
substrate-network = { path = "../network" }
substrate-client = { path = "../client" }
substrate-client-db = { path = "../client/db" }
substrate-codec = { path = "../codec" }
substrate-executor = { path = "../executor" }
substrate-extrinsic-pool = { path = "../extrinsic-pool" }
substrate-rpc = { path = "../rpc" }
substrate-rpc-servers = { path = "../rpc-servers" }
substrate-telemetry = { path = "../telemetry" }
