[package]
name = "substrate-runtime-primitives"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
num-traits = { version = "0.2", default_features = false }
substrate-runtime-std = { path = "../../runtime-std", default_features = false }
substrate-runtime-io = { path = "../../runtime-io", optional = true }
substrate-codec = { path = "../../codec", default_features = false }
substrate-primitives = { path = "../../primitives", default_features = false }

[features]
default = ["std"]
std = [
	"num-traits/std",
	"substrate-runtime-std/std",
	"substrate-runtime-io",
	"substrate-codec/std",
	"substrate-primitives/std",
]
