[package]
name = "substrate-runtime-executive"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
hex-literal = "0.1.0"
serde = { version = "1.0", default_features = false }
serde_derive = { version = "1.0", optional = true }
parity-codec = { path = "../../../codec", default_features = false }
sr-std = { path = "../../sr-std", default_features = false }
sr-io = { path = "../../sr-io", default_features = false }
substrate-runtime-support = { path = "../../srml/support", default_features = false }
sr-primitives = { path = "../../sr-primitives", default_features = false }
substrate-runtime-system = { path = "../system", default_features = false }

[dev-dependencies]
substrate-primitives = { path = "../../primitives" }
substrate-runtime-balances = { path = "../balances" }
parity-codec-derive = { path = "../../../codec/derive" }

[features]
default = ["std"]
std = [
	"sr-std/std",
	"substrate-runtime-support/std",
	"serde/std",
	"serde_derive",
	"parity-codec/std",
	"sr-primitives/std",
	"sr-io/std",
	"substrate-runtime-system/std",
]
