[package]
name = "substrate-primitives"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
rstd = { package = "sr-std", path = "../sr-std", default-features = false }
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
rustc-hex = { version = "2.0", default-features = false }
serde = { version = "1.0", optional = true, features = ["derive"] }
twox-hash = { version = "1.3.0", default-features = false }
byteorder = { version = "1.3.1", default-features = false }
primitive-types = { version = "0.5.0", default-features = false, features = ["codec"] }
impl-serde = { version = "0.1", optional = true }
log = { version = "0.4", optional = true }
wasmi = { version = "0.5.0", optional = true }
hash-db = { version = "0.15.2", default-features = false }
hash256-std-hasher = { version = "0.15.2", default-features = false }
ed25519-dalek = { version = "1.0.0-pre.1", default-features = false, features = ["u64_backend"], optional = true }
base58 = { version = "0.1", optional = true }
blake2-rfc = { version = "0.2.18", default-features = false, optional = true }
schnorrkel = { version = "0.8.5", features = ["preaudit_deprecated"], default-features = false, optional = true }
rand = { version = "0.6", optional = true }
sha2 = { version = "0.8", optional = true }
substrate-bip39 = { version = "0.3.1", optional = true }
tiny-bip39 = { version = "0.6.1", optional = true }
hex = { version = "0.4", default-features = false, optional = true }
regex = { version = "1.1", optional = true }
num-traits = { version = "0.2", default-features = false }
zeroize = { version = "0.9.2", default-features = false }
lazy_static = { version = "1.3", default-features = false, optional = true }
parking_lot = { version = "0.9.0", optional = true }

[dev-dependencies]
substrate-serializer = { path = "../serializer" }
pretty_assertions = "0.6"
hex-literal = "0.2"
rand = "0.6"
criterion = "0.2"

[[bench]]
name = "benches"
harness = false

[lib]
bench = false

[features]
default = ["std"]
std = [
	"with_crypto",
	"log",
	"wasmi",
	"lazy_static",
    "parking_lot",
	"primitive-types/std",
	"primitive-types/serde",
	"primitive-types/byteorder",
	"primitive-types/rustc-hex",
	"primitive-types/libc",
	"impl-serde",
	"codec/std",
	"hash256-std-hasher/std",
	"hash-db/std",
	"rstd/std",
	"serde",
	"rustc-hex/std",
	"twox-hash/std",
	"blake2-rfc/std",
	"ed25519-dalek/std",
	"hex/std",
	"base58",
	"substrate-bip39",
	"tiny-bip39",
	"serde",
	"byteorder/std",
	"rand",
	"sha2",
	"schnorrkel/std",
	"regex",
	"num-traits/std",
	"zeroize/std"
]

with_crypto = [
	"ed25519-dalek",
	"blake2-rfc",
	"schnorrkel",
	"hex",
]
