[package]
name = "fuzzer"
version = "0.1.0"
authors = ["Ashley <ashley.ruglys@gmail.com>"]
edition = "2018"

[dependencies]
honggfuzz = "0.5"
sr-primitives = { path = ".." }
arbitrary = "*"

[workspace]

[[bin]]
name = "biguint"
path = "src/biguint.rs"