[package]
name = "substrate-transaction-pool"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.0.0" }
derive_more = "0.15.0"
futures = { version = "0.3.1", features = ["compat"] }
log = "0.4.8"
parking_lot = "0.9.0"
primitives = { package = "substrate-primitives",  path = "../../primitives/core" }
sr-api = { path = "../../primitives/sr-api" }
sr-primitives = { path = "../../primitives/sr-primitives" }
txpool = { package = "substrate-transaction-graph", path = "./graph" }
txpool-api = { package = "substrate-transaction-pool-api", path = "../../primitives/transaction-pool" }
txpool-runtime-api = { package = "substrate-transaction-pool-runtime-api", path = "../../primitives/transaction-pool/runtime-api" }
client-api = { package = "substrate-client-api", path = "../api" }
# TODO [ToDr] USe traits instead?
client = { package = "substrate-client", path = "../" }

[dev-dependencies]
keyring = { package = "substrate-keyring", path = "../../primitives/keyring" }
test-client = { package = "substrate-test-runtime-client", path = "../../test/utils/runtime/client" }
