[package]
name = "pallet-bridge"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false }
fg_primitives = { package = "sp-finality-grandpa", path = "../../primitives/finality-grandpa" }
frame-support = { version = "2.0.0", default-features = false, path = "../support" }
frame-system = { package = "frame-system", path = "../system", default-features = false }
hash-db = { version = "0.15.2", default-features = false }
primitives = { package = "sp-core",  path = "../../primitives/core", default-features = false }
session = { package = "pallet-session", path = "../session", default-features = false }
serde = { version = "1.0", optional = true }
sp-runtime = { version = "2.0.0", default-features = false, path = "../../primitives/runtime" }
sp-trie = { version = "2.0.0", path = "../../primitives/trie", default-features = false }

[dev-dependencies]
sp-io = { version = "2.0.0", default-features = false, path = "../../primitives/io" }
sp-state-machine = { version = "2.0.0", path = "../../primitives/state-machine" }

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"primitives/std",
	"session/std",
	"sp-runtime/std",
	"sp-trie/std",
	"sp-io/std",
]
