[package]
description = "Gossiping for the Substrate network protocol"
name = "substrate-network-gossip"
version = "2.0.0"
license = "GPL-3.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
async-std = "1.0"
log = "0.4.8"
futures01 = { package = "futures", version = "0.1.29" }
futures-preview = { version = "0.3.0-alpha.19", features = ["compat"] }
futures-timer = "0.4.0"
lru-cache = "0.1.2"
libp2p = { version = "0.13.0", default-features = false, features = ["libp2p-websocket"] }
network = { package = "substrate-network", path = "../network" }
parking_lot = "0.9.0"
sr-primitives = { path = "../../primitives/sr-primitives" }
