[package]
name = "substrate-client-db"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
parking_lot = "0.4"
log = "0.3"
kvdb = "0.1"
kvdb-rocksdb = "0.1.3"
hashdb = "0.2.1"
memorydb = "0.2.1"
substrate-primitives = { path = "../../primitives" }
substrate-client = { path = "../../client" }
substrate-state-machine = { path = "../../state-machine" }
substrate-codec = { path = "../../codec" }
substrate-codec-derive = { path = "../../codec/derive" }
substrate-executor = { path = "../../executor" }
substrate-state-db = { path = "../../state-db" }
substrate-runtime-support = { path = "../../../runtime/support" }
substrate-runtime-primitives = { path = "../../../runtime/primitives" }

[dev-dependencies]
kvdb-memorydb = "0.1"
