[package]
name = "substrate-consensus-uncles"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Generic uncle inclusion utilities for consensus"
edition = "2018"

[dependencies]
interfaces = { package = "substrate-client-interfaces", path = "../../interfaces" }
primitives = { package = "substrate-primitives", path = "../../../primitives/core" }
sr-primitives = {  path = "../../../primitives/sr-primitives" }
paint-authorship = {  path = "../../../paint/authorship" }
consensus_common = { package = "substrate-consensus-common", path = "../../../primitives/consensus/common" }
inherents = { package = "substrate-inherents", path = "../../../primitives/inherents" }
log = "0.4.8"
