[package]
description = "Connectivity manager based on reputation"
homepage = "http://parity.io"
license = "GPL-3.0"
name = "substrate-peerset"
version = "1.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
futures = "0.1"
libp2p = { git = "https://github.com/libp2p/rust-libp2p", rev = "a953b613cf543708ec3aa65c66921934310f8069", default-features = false }
linked-hash-map = "0.5"
log = "0.4"
lru-cache = "0.1.2"
serde_json = "1.0.24"