[package]
name = "node-executor"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Substrate node implementation in Rust."
edition = "2018"

[dependencies]
trie-root = "0.15.2"
codec = { package = "parity-scale-codec", version = "1.0.0" }
runtime_io = { package = "sr-io", path = "../../../primitives/sr-io" }
state_machine = { package = "substrate-state-machine", path = "../../../primitives/state-machine" }
substrate-executor = { path = "../../../client/executor" }
primitives = { package = "substrate-primitives", path = "../../../primitives/core" }
trie = { package = "substrate-trie", path = "../../../primitives/trie" }
node-primitives = { path = "../primitives" }
node-runtime = { path = "../runtime" }

[dev-dependencies]
node-testing = { path = "../testing" }
test-client = { package = "substrate-test-client", path = "../../../test/utils/client" }
sr-primitives = { path = "../../../primitives/sr-primitives" }
runtime_support = { package = "paint-support", path = "../../../palette/support" }
balances = { package = "paint-balances", path = "../../../palette/balances" }
transaction-payment = { package = "paint-transaction-payment", path = "../../../palette/transaction-payment" }
session = { package = "paint-session", path = "../../../palette/session" }
system = { package = "paint-system", path = "../../../palette/system" }
timestamp = { package = "paint-timestamp", path = "../../../palette/timestamp" }
treasury = { package = "paint-treasury", path = "../../../palette/treasury" }
contracts = { package = "paint-contracts", path = "../../../palette/contracts" }
grandpa = { package = "paint-grandpa", path = "../../../palette/grandpa" }
indices = { package = "paint-indices", path = "../../../palette/indices" }
wabt = "0.9.2"
criterion = "0.3.0"

[features]
wasmtime = [
    "substrate-executor/wasmtime",
]
wasmi-errno = [
	"substrate-executor/wasmi-errno",
]
stress-test = []

[[bench]]
name = "bench"
harness = false

