[package]
name = "srml-system-rpc"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
client = { package = "substrate-client", path = "../../../core/client" }
jsonrpc-core = "13.2.0"
jsonrpc-core-client = "13.2.0"
jsonrpc-derive = "13.2.0"
jsonrpc-pubsub = "13.2.0"
keyring = { package = "substrate-keyring", path = "../../../core/keyring" }
log = "0.4.8"
codec = { package = "parity-scale-codec", version = "1.0.0" }
serde = { version = "1.0.101", features = ["derive"] }
sr-primitives = { path = "../../../core/sr-primitives" }
substrate-primitives = { path = "../../../core/primitives" }
rpc-primitives = { package = "substrate-rpc-primitives", path = "../../../core/rpc/primitives" }
transaction_pool = { package = "substrate-transaction-pool", path = "../../../core/transaction-pool" }
srml-system-rpc-runtime-api = { path = "./runtime-api" }

[dev-dependencies]
node-testing = { path = "../../../node/testing" }
node-runtime = { path = "../../../node/runtime" }
env_logger = "0.6.2"
futures03 = { package = "futures-preview", version = "=0.3.0-alpha.19" }
