{{- if .Values.validator.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: substrate-secrets
  labels:
    app: substrate
type: Opaque
data:
{{ toYaml .Values.validator.secrets | default "{}" | indent 2 }}
{{- end }}
