[package]
name = "node-cli"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Substrate node implementation in Rust."

[dependencies]
log = "0.4"
tokio = "0.1.7"
exit-future = "0.1"
substrate-cli = { path = "../../core/cli" }
substrate-primitives = { path = "../../core/primitives" }
node-runtime = { path = "../runtime" }
node-service = { path = "../service" }
hex-literal = "0.1"
substrate-service = { path = "../../core/service" }
