[package]
name = "substrate-consensus-babe-primitives"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Primitives for BABE consensus"
edition = "2018"

[dependencies]
substrate-client = { path = "../../../client", default-features = false }
rstd = { package = "sr-std", path = "../../../sr-std", default-features = false }
sr-primitives = {  path = "../../../sr-primitives", default-features = false }
app-crypto = { package = "substrate-application-crypto", path = "../../../application-crypto", default-features = false }
slots = { package = "substrate-consensus-slots", path = "../../slots", optional = true }
schnorrkel = { version = "0.8.5", features = ["preaudit_deprecated"], optional = true }
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false }

[features]
default = ["std"]
std = [
	"full_crypto",
	"rstd/std",
	"sr-primitives/std",
	"substrate-client/std",
	"codec/std",
	"schnorrkel",
	"slots",
	"app-crypto/std",
]

# This feature enables all crypto primitives for `no_std` builds like microcontrollers 
# or Intel SGX. 
# For the regular wasm runtime builds this should not be used.
full_crypto = []
