[package]
name = "node-executor"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Substrate node implementation in Rust."

[dependencies]
hex-literal = "0.1"
triehash = "0.2"
parity-codec = { path = "../../codec" }
sr-io = { path = "../../core/sr-io" }
substrate-state-machine = { path = "../../core/state-machine" }
substrate-executor = { path = "../../core/executor" }
substrate-primitives = { path = "../../core/primitives" }
node-primitives = { path = "../primitives" }
node-runtime = { path = "../runtime" }

[dev-dependencies]
substrate-keyring = { path = "../../core/keyring" }
sr-primitives = { path = "../../core/sr-primitives" }
substrate-runtime-support = { path = "../../core/runtime/support" }
substrate-runtime-balances = { path = "../../core/runtime/balances" }
substrate-runtime-session = { path = "../../core/runtime/session" }
substrate-runtime-staking = { path = "../../core/runtime/staking" }
substrate-runtime-system = { path = "../../core/runtime/system" }
substrate-runtime-consensus = { path = "../../core/runtime/consensus" }
substrate-runtime-timestamp = { path = "../../core/runtime/timestamp" }
substrate-runtime-treasury = { path = "../../core/runtime/treasury" }
