[package]
name = "substrate-consensus-aura-primitives"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Primitives for Aura consensus"
edition = "2018"

[dependencies]
parity-codec = { version = "4.1.1", default-features = false }
substrate-client = { path = "../../../client", default-features = false }
app-crypto = { package = "substrate-application-crypto", path = "../../../application-crypto", default-features = false }
rstd = { package = "sr-std", path = "../../../sr-std", default-features = false }
sr-primitives = {  path = "../../../sr-primitives", default-features = false }

[features]
default = ["std"]
std = [
	"rstd/std",
	"parity-codec/std",
	"sr-primitives/std",
	"substrate-client/std",
	"app-crypto/std",
]
