[package]
name = "substrate-consensus-aura-primitives"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Primitives for Aura consensus"
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false }
substrate-client = { path = "../../../client", default-features = false }
app-crypto = { package = "substrate-application-crypto", path = "../../../application-crypto", default-features = false }
rstd = { package = "sr-std", path = "../../../sr-std", default-features = false }
sr-primitives = { path = "../../../sr-primitives", default-features = false }

[features]
default = ["std"]
std = [
	"full_crypto",
	"rstd/std",
	"codec/std",
	"sr-primitives/std",
	"substrate-client/std",
	"app-crypto/std",
]

# This feature enables all crypto primitives for `no_std` builds like microcontrollers 
# or Intel SGX. 
# For the regular wasm runtime builds this should not be used.
full_crypto = []