name: Check Links

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: gaurav-nelson/github-action-markdown-link-check@28631ee73c4024e27af2a44ee611c97fe0012a34
      with:
        use-quiet-mode: 'yes'
        config-file: '.github/workflows/mlc_config.json'
